### ISSUE TITLE
 kernel panic with voodoops2trackpad identify touchpad command failed,

### ISSUE THREAD

**Issue by racso25** [AskDavis/LG-Gram-17Z90N#12]
> Mornig, who can help me with kernel panic with voodoops2trackpad identify touchpad command failed, I have no idea what will be happend with this, I am used last EFI folder and I can not enter to my instalation of BigSur, pleasse help me.

The trackpad does not work in the installation. You have to plug in your mouse for installation. Chances are you didn't follow the bios settings and you have a kernel panic.

Bios settings? Phoenix settigs?

_Originally posted by @daniyo27 in https://github.com/AskDavis/LG-Gram-17Z90N/issues/10#issuecomment-999785188_

**Comment by daniyo27** [comment]
1. BIOS Settings
Hold F2 to enter BIOS on boot up
Press CTRL-ALT-F7 to open Advanced Options
Main - Boot Features - Quick Boot => Disabled
Advanced - Intel Advanced Menu - CPU Configuration - Software Guard Extentsions (SGX) => Disabled
Advanced - Intel Advanced Menu - Power & Performance - "CPU - Power Management Control" - CPU Lock Configuration - CFG Lock => Disabled and Overclocking Lock => Disabled
Advanced - Intel Advanced Menu - System Agent (SA) Configuration - Graphics Configuration - DVMT Pre-Allocated => 64M
Advanced - Intel Advanced Menu - PCH-IO Configuration - Security Configuration - Force unlock on all GPIO pads => Enabled (Thanks 1OldSWguy)
Advanced - Intel Advanced Menu - Platform Settings - System Time and Alarm Source => Legacy RTC
Exit - Exit Saving Changes

**Comment by racso25** [comment]
i am continúe having problems with kext and kernel panics,

**Comment by daniyo27** [comment]
You keep saying you have kernel panic yet you don't even post screenshots? How are we supposed to know what exactly is wrong?

**Comment by racso25** [comment]
This afternoom i am going to tacke screen capture with issuess, but i am
having problems with kext and efi

**Comment by racso25** [comment]
Here my screenshot and video
![IMG_20211225_230656](https://user-images.githubusercontent.com/96356956/147394835-2f8c76a2-9dd6-47b1-86e9-376e9e88ced5.jpg)
![IMG_20211225_231120](https://user-images.githubusercontent.com/96356956/147394837-e9ec0b01-b171-42aa-8320-0e0556c7542f.jpg)
![IMG_20211225_231218](https://user-images.githubusercontent.com/96356956/147394839-f67c704d-d2a2-4c4a-8d9d-f6d16e6d0376.jpg)
![IMG_20211225_231318](https://user-images.githubusercontent.com/96356956/147394841-dbef8426-5d8a-4a3e-adc6-c5816aa53e84.jpg)
![IMG_20211225_231408](https://user-images.githubusercontent.com/96356956/147394842-c26cb74d-7060-40c4-b201-65c2ffcb5f89.jpg)
![IMG_20211225_231504](https://user-images.githubusercontent.com/96356956/147394843-3475555a-80f1-4d5f-afd5-880b10a91d3a.jpg)
![IMG_20211225_231541](https://user-images.githubusercontent.com/96356956/147394846-f01fa5ce-9479-4920-a9e0-1f8183209140.jpg)
![IMG_20211225_231611](https://user-images.githubusercontent.com/96356956/147394848-2ca9a1b3-bb22-4ffd-8c2a-ad5501f3b290.jpg)
![IMG_20211225_231902](https://user-images.githubusercontent.com/96356956/147394849-3d9338f3-4bf9-4874-957c-600e9d2272b9.jpg)
![IMG_20211225_233411](https://user-images.githubusercontent.com/96356956/147394851-fd64e8ad-cbcc-44ad-bd1c-e2490ce3d73e.jpg)

**Comment by racso25** [comment]
Here you are my screenshot

**Comment by racso25** [comment]
> You keep saying you have kernel panic yet you don't even post screenshots? How are we supposed to know what exactly is wrong?
[
](https://github.com/AskDavis/LG-Gram-17Z90N/issues/12#issuecomment-1001080359)

**Comment by racso25** [comment]
> You keep saying you have kernel panic yet you don't even post screenshots? How are we supposed to know what exactly is wrong?

https://github.com/AskDavis/LG-Gram-17Z90N/issues/12#issuecomment-1001080359) take a look to my screenshot and if you can help me, do it please
