### ISSUE TITLE
Trackpad not working fix

### ISSUE THREAD

**Issue by daniyo27** [AskDavis/LG-Gram-17Z90N#17]
Hi @AskDavis,

Your new config just uploaded contains this flag set to Enabled which actually should be **Disabled!**
`<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooInput.kext</string>`

The actual one that should be **Enabled** is: (Note the **I2C**)
`<string>VoodooI2C.kext/Contents/PlugIns/VoodooInput.kext</string>`

**Comment by daniyo27** [comment]
as a side note, it seems like your EFI crashes upon wake with a USB-C dock plugged in.

**Comment by AskDavis** [comment]
hey thanks! I tired disabling that kext and enabling the other and it still doesnt work for me. i might revert back to last voodoo and see if it works then?

**Comment by daniyo27** [comment]
Hmm it seems to work for mine with my own efi configuration adapted from the other people. I updated all the kexts as of yesterday.

https://github.com/AskDavis/LG-Gram-17Z90N/issues/16#issuecomment-1272375439

**Comment by AskDavis** [comment]
so I just tried yours and with two finger click it does not right click. not sure why mine would be different? do you have tap to click on?

**Comment by daniyo27** [comment]
I have tap to click on and silent/force clicking OFF

**Comment by AskDavis** [comment]
if you turn off tap to click can you still two finger right click?
Thanks :)

**Comment by daniyo27** [comment]
Hmm it was not working until I toggled it on and off a bunch of times. Now it works with tap to click OFF and I can still two finger right click

<img width="780" alt="Screen Shot 2022-10-08 at 12 27 35 PM" src="https://user-images.githubusercontent.com/11026113/194724217-c498417f-91ec-48c0-8fb4-26c8ba4de1a8.png">

**Comment by daniyo27** [comment]
Spoke too soon... it seems like the behaviour is intermittent. If you just lightly tap for right click it works always...

**Comment by AskDavis** [comment]
okay i added the older voodoo and it fixed my issue with the trackpad
Also i changed my EFI to yours in this repo! thanks again for your help!

**Comment by daniyo27** [comment]
Cool! I haven't had the chance to add the @1OldSWGuy 's brightness patches. Maybe if you can add that in?

[https://github.com/AskDavis/LG-Gram-17Z90N/issues/16#issuecomment-1248793981](https://github.com/AskDavis/LG-Gram-17Z90N/issues/16#issuecomment-1248793981)
[https://github.com/AskDavis/LG-Gram-17Z90N/issues/16#issuecomment-1249718595](https://github.com/AskDavis/LG-Gram-17Z90N/issues/16#issuecomment-1249718595)

**Comment by AskDavis** [comment]
okay added those as well and tested that they are working! thanks!
