### ISSUE TITLE
The keyboard and mouse doesn't work

### ISSUE THREAD

**Issue by brian31405** [AskDavis/LG-Gram-17Z90N#2]
I'm booting on to a 11.3.1 installer when I found out this problem. The installer keep telling me to turn on my keyboard and mouse. I tried to load up a 11.2.2 installer, It crashed and restart before the installer could done it's job. I owned an i5 version of 17z90n

**Comment by underdoggum** [comment]
For anyone else having this issue, plugging in an external, wired mouse into the left-side USB port worked well for me while installing Big Sur on the i7 17Z90N

**Comment by 1OldSWguy** [comment]
Keyboard and TrackPad work flawlessly on my 17Z90N (I'm on Opencore 0.7.3).  Use VoodooPS2 for keyboard; no BIOS settings or patches required.  Use VoodooI2C with VoodooI2CHID for TrackPad; requires BIOS setting change to force unlock of GPIO pads.  I have not tested without using the SSDT-XOSI and _OSI to XOSI rename patch, but I think it will work without that.  The BIOS setting can be found in the Intel Advanced Menu
PCH-IO Configuration --> Security Configuration --> Force unlock on all GPIO pads [Enabled]

It's also possible that other patches/kexts I'm using are necessary to enabl the TrackPad to function.

**Comment by brian31405** [comment]
[Update]
I discovered my 17z90n using PM981A as the primary storage, After switching to an SN550 Solve most of the problems I mentioned, Also For those who still suffer from the faulty trackpad and battery settings, Add ECEnabler.kext to your kext folder and config.plist, I confirmed it fixes the problems.

**Comment by AskDavis** [comment]
Thank you everyone! this was greatly helpful and ill update the GitHub to 0.7.4 later this week. I was curious if you guys got the webcam to work at all? Thanks again!!!

**Comment by 1OldSWguy** [comment]
Yes, webcam works. It is a USB device so it has to be mapped. Let me know if you want me to upload my USBMap kext.

**Comment by 1OldSWguy** [comment]
It's easy to do using the USBMap tool from CorpNewt, but you have to do it prior to upgrading to 11.3+ as the XhciPortLimit patch can no longer be used.  I completed it running 11.2.3 and it is working for me.  I've attached my result.
[USBMap-17Z90N.zip](https://github.com/AskDavis/LG-Gram-17Z90N/files/7316646/USBMap-17Z90N.zip)
