### ISSUE TITLE
Hardware Accelelator disable

### ISSUE THREAD

**Issue by rayqusa** [AskDavis/LG-Gram-17Z90N#20]
I have this laptop, I want to hackintosh it. I heard rumor that ice lake processor got disable hardware accelerator. does it already fixed? thank you

**Comment by jasonbrowne44** [comment]
The internal Intel Iris Plus Graphics GPU on the LG-Gram 17Z90N will support weak hardware acceleration (Metal for example).  This laptop works for most non-GPU intensive applications on Monterey 12.6.  Here is the report from System Report:

Intel Iris Plus Graphics:

  Chipset Model:	Intel Iris Plus Graphics
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x8a52
  Revision ID:	0x0007
  Metal Family:	Supported, Metal GPUFamily macOS 2
  Displays:
Display:
  Resolution:	2048 x 1280
  UI Looks like:	2048 x 1280
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal
