### ISSUE TITLE
Compatibility of later LG Gram 17 models

### ISSUE THREAD

**Issue by jc-bao** [AskDavis/LG-Gram-17Z90N#24]
I am using an LG Gram 17 (2021) with an i7-1195G7 processor, and I'm curious about the compatibility of this repository with my specific laptop model. Any information or guidance would be highly appreciated!

Additional Information:

Laptop Model: LG Gram 17 (2021) 17z95p
Processor: Intel Core i7-1195G7

**Comment by giovanni-gatto-76** [comment]
11th gen GPU is NOT supported at all afaik

**Comment by jc-bao** [comment]
Yeah, I think so. Thanks for your response!
