### ISSUE TITLE
Can someone confirm BIOS have to be re-entered ??

### ISSUE THREAD

**Issue by drewwiens** [AskDavis/LG-Gram-17Z90N#5]
"If the system Crashes, Kernal Panics, or you manually shut it down you will have to re-enter BIOS settings above"

^ Is it true? I just have never seen a laptop that loses BIOS settings after a reboot or kernel panic

Trying to decide whether hackintoshing the Gram 17 will be worth it

**Comment by 1OldSWguy** [comment]
Yes, all advanced settings are returned to default every time I manually power off to recover from a hang/lock-up.  I think hacking the Gram is worth it.  It runs Big Sur like a dream.
