### ISSUE TITLE
Added installation instruction

### ISSUE THREAD

**Issue by underdoggum** [AskDavis/LG-Gram-17Z90N#6]
Thank you for writing up this guide! It's surely saved me a lot of time on my 17Z90N.

Under the BIOS settings, we also must disable "Secure Boot Option" in the Installation section of the README
Security - Secure Boot Configuration - Secure Boot Option - Disabled

**Comment by AskDavis** [comment]
Thank you! ill add this option to the GitHub, it was off by default for me, but would be good to check!

Jacob

**Comment by AskDavis** [comment]
Added to BIOS instruction.
